
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int LTHEN = 84;
  public static final int OP_SHL = 94;
  public static final int SHORT = 5;
  public static final int OP_DEC = 46;
  public static final int IDENTIFIER = 97;
  public static final int STRGN = 11;
  public static final int IMPLEMENTS = 26;
  public static final int OP_LOR = 53;
  public static final int ASS_AND = 62;
  public static final int TIL = 77;
  public static final int ASS_XOR = 63;
  public static final int SOR = 86;
  public static final int CATCH = 91;
  public static final int COMMA = 65;
  public static final int THROW = 90;
  public static final int OP_NE = 51;
  public static final int EQU = 71;
  public static final int DOUBLE = 9;
  public static final int TRANSIENT = 20;
  public static final int LITERAL = 98;
  public static final int PROTECTED = 17;
  public static final int QUE = 88;
  public static final int OP_DIM = 27;
  public static final int FINAL = 15;
  public static final int FLOAT = 8;
  public static final int OP_GE = 48;
  public static final int PACKAGE = 12;
  public static final int OP_INC = 45;
  public static final int ASS_SUB = 58;
  public static final int MOD = 82;
  public static final int CLASS = 24;
  public static final int ASS_SHR = 60;
  public static final int SUPER = 43;
  public static final int ABSTRACT = 14;
  public static final int OP_LAND = 52;
  public static final int ASS_SHL = 59;
  public static final int NATIVE = 22;
  public static final int PLUS = 79;
  public static final int LONG = 7;
  public static final int WHILE = 35;
  public static final int EXTENDS = 29;
  public static final int ASS_OR = 64;
  public static final int INTERFACE = 25;
  public static final int CHAR = 3;
  public static final int BOOLEAN = 2;
  public static final int OP_LE = 47;
  public static final int ASS_MUL = 54;
  public static final int SWITCH = 33;
  public static final int SEMIC = 66;
  public static final int DO = 36;
  public static final int ASS_MOD = 56;
  public static final int OPENKEYS = 69;
  public static final int FOR = 37;
  public static final int DIV = 81;
  public static final int VOID = 10;
  public static final int PUBLIC = 16;
  public static final int RETURN = 39;
  public static final int MULT = 68;
  public static final int ELSE = 34;
  public static final int TRY = 40;
  public static final int OP_EQ = 50;
  public static final int BREAK = 38;
  public static final int CLOSEKEYS = 70;
  public static final int DOT = 67;
  public static final int INT = 6;
  public static final int THROWS = 28;
  public static final int AMPER = 87;
  public static final int EOF = 0;
  public static final int THIS = 42;
  public static final int DEFAULT = 31;
  public static final int OP_SHRR = 96;
  public static final int JNULL = 44;
  public static final int IMPORT = 13;
  public static final int ASS_ADD = 57;
  public static final int ASS_DIV = 55;
  public static final int MINUS = 80;
  public static final int ASS_SHRR = 61;
  public static final int error = 1;
  public static final int CLOSEPAR = 73;
  public static final int SYNCHRONIZED = 23;
  public static final int FINALLY = 92;
  public static final int CONTINUE = 89;
  public static final int IF = 32;
  public static final int INSTANCEOF = 49;
  public static final int COLON = 74;
  public static final int VOLATILE = 21;
  public static final int CASE = 30;
  public static final int OPENBRAC = 75;
  public static final int BTHEN = 83;
  public static final int NEW = 93;
  public static final int CLOSEBRAC = 76;
  public static final int BYTE = 4;
  public static final int PRIVATE = 18;
  public static final int STATIC = 19;
  public static final int OPENPAR = 72;
  public static final int BOOLLIT = 41;
  public static final int OP_SHR = 95;
  public static final int NE = 78;
  public static final int XOR = 85;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOLEAN",
  "CHAR",
  "BYTE",
  "SHORT",
  "INT",
  "LONG",
  "FLOAT",
  "DOUBLE",
  "VOID",
  "STRGN",
  "PACKAGE",
  "IMPORT",
  "ABSTRACT",
  "FINAL",
  "PUBLIC",
  "PROTECTED",
  "PRIVATE",
  "STATIC",
  "TRANSIENT",
  "VOLATILE",
  "NATIVE",
  "SYNCHRONIZED",
  "CLASS",
  "INTERFACE",
  "IMPLEMENTS",
  "OP_DIM",
  "THROWS",
  "EXTENDS",
  "CASE",
  "DEFAULT",
  "IF",
  "SWITCH",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "BREAK",
  "RETURN",
  "TRY",
  "BOOLLIT",
  "THIS",
  "SUPER",
  "JNULL",
  "OP_INC",
  "OP_DEC",
  "OP_LE",
  "OP_GE",
  "INSTANCEOF",
  "OP_EQ",
  "OP_NE",
  "OP_LAND",
  "OP_LOR",
  "ASS_MUL",
  "ASS_DIV",
  "ASS_MOD",
  "ASS_ADD",
  "ASS_SUB",
  "ASS_SHL",
  "ASS_SHR",
  "ASS_SHRR",
  "ASS_AND",
  "ASS_XOR",
  "ASS_OR",
  "COMMA",
  "SEMIC",
  "DOT",
  "MULT",
  "OPENKEYS",
  "CLOSEKEYS",
  "EQU",
  "OPENPAR",
  "CLOSEPAR",
  "COLON",
  "OPENBRAC",
  "CLOSEBRAC",
  "TIL",
  "NE",
  "PLUS",
  "MINUS",
  "DIV",
  "MOD",
  "BTHEN",
  "LTHEN",
  "XOR",
  "SOR",
  "AMPER",
  "QUE",
  "CONTINUE",
  "THROW",
  "CATCH",
  "FINALLY",
  "NEW",
  "OP_SHL",
  "OP_SHR",
  "OP_SHRR",
  "IDENTIFIER",
  "LITERAL"
  };
}

