
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analisadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int div = 5;
  public static final int mais = 2;
  public static final int par_abre = 6;
  public static final int mult = 4;
  public static final int num = 8;
  public static final int EOF = 0;
  public static final int menos = 3;
  public static final int error = 1;
  public static final int par_fecha = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mais",
  "menos",
  "mult",
  "div",
  "par_abre",
  "par_fecha",
  "num"
  };
}

